name: Build and deploy

on:
  label:
    types: 
    - created
    - edited
    - deleted

jobs:
  build-and-deploy:
    if: github.event.label.name == 'published'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Install theme
      run: composer install --prefer-dist --no-progress
    
    - name: Build site
      uses: Cecilapp/Cecil-Action@v3

    - name: Deploy site
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: arnaud@ligny.org
